# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UA Banking Assistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UA Banking Assistant

pod 'Alamofire', '~> 4.8.2'
pod 'AlamofireObjectMapper'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Google-Mobile-Ads-SDK'

end
